Melhorando e modernizando o algoritmo de dijkstra.
splucs/Competitive-Programming pull request #4
Opened 2022-08-31 01:15 UTC by thelostgus

Melhorei o algoritmo permitindo que além do retorno do menor caminho também retorne a trajetória do caminho por entre os nodos, além do mais, atualizei algumas funcionalidades para versões modernas oriundas do C++ 14 e 17.

2022-09-16 18:01 UTC, splucs requested changes

2022-09-16 18:01 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +				path.push_back(v);
Isso está errado. Pra pegar o melhor caminho você precisa guardar de uma array `prev` tal que `prev[v]` é o nó de onde vem o melhor caminho de `s` a `v`.
No começo você faz `prev[s]=-1`. Aqui você precisa atualizar `prev[v] = u`. No final você precisa fazer:
```
for (int u = t; prev[u] != -1; u = prev[u]) {
    path.push_back(u);
}
reverse(path.begin(), path.end());
```

2022-09-16 18:01 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +	// Retorna o valor total do caminho e o caminho
Comentário desnecessário, isso é óbvio pelo código.
No geral códigos de maratona tem que ser curtos e sucintos senão eles assustam.

2022-09-16 18:01 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +			// v -> No destiono
Prefiro manter o código limpo de comentários pra poder copiar e colar direto no macacário. Se o código precisa de alguma explicação eu coloco no comentário acima ou no parágrafo no macacário.
No geral códigos de maratona tem que ser curtos e sucintos senão eles assustam.

2022-09-16 18:01 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +array<int, MAXN> dist;
Qual o impacto de performance nisso? Prefiro manter o mais próximo do C possível.

2022-09-16 18:01 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +	return ivi(dist[t], path);
Eu pessoalmente não acho que deveríamos incluir o problema de achar o caminho no código base. É uma variante bem simples de se adicionar ao código na hora do contest.
Os códigos do macacário tem que ser simples para não assustarem e caberem no macacário. Devem também ser facilmente extendíveis para que possam ser alterados para qualquer variante do problema. O código base vai ficar assustador se tentarmos resolver todas as variantes.

2022-09-16 18:01 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +using namespace std;
Poderia agrupar os includes junto com os outros abaixo?

2022-09-16 18:01 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +#include <iostream>
`#include <iostream>` -> `#include <array>`
Não usamos iostream nesse repositório pois não usamos `cin` e `cout`, apenas `scanf` e `printf`.

2022-10-09 18:05 UTC, leaomatheus commented on Macacário/Graphs/dijkstra.cpp
> +		int u{pq.begin()->second};
Qual a diferenca entre {} e = ? Existe algum motivo pra trocar de um pra outro?

2022-10-11 22:27 UTC, wuerges commented on Macacário/Graphs/dijkstra.cpp
> +		int u{pq.begin()->second};
O {} é a maneira "padrão" de inicializar no C++ hoje. 
Neste caso não faz muita diferença. 

O que ele garante é que o tipo do valor a ser atribuído para o `u` é de fato um `int`. Ele ajudaria a prevenir um overflow.

2022-11-30 17:58 UTC, thelostgus commented on Macacário/Graphs/dijkstra.cpp
> +	// Retorna o valor total do caminho e o caminho
Como estudante de computação em final de curso, o que me assusta é um algoritmo que deveria retornar um caminho não retornar um caminho mas a somas dos pesos do menor caminho, é literalmente colocar um caso particular de situação como genérico e o genérico como caso particular. Mesmo com anos de experiência em C e C++ de primeira o código parecia incompreensível e sem sentido.

2022-11-30 18:01 UTC, thelostgus commented on Macacário/Graphs/dijkstra.cpp
> +			// v -> No destiono
Assusta mais não entender o que você mesmo esta fazendo ou modificando. E aquele código de dijkstra foge da proposta de retorno pelo próprio dijkstra.

2022-11-30 18:03 UTC, thelostgus commented on Macacário/Graphs/dijkstra.cpp
> +array<int, MAXN> dist;
Se tu ler a documentação do C++ ou ao menos algum livro bom de C++ 14 completo não estaria me fazendo uma pergunta desse nível enquanto da a entender que sabe mais sobre a linguagem e programação em si mais do que qualquer um.

2022-11-30 18:05 UTC, thelostgus commented on Macacário/Graphs/dijkstra.cpp
> +	return ivi(dist[t], path);
Irmão, Dijkstra chora e se fosse simples assim eu não teria visto tanta gente boa se debatendo em cima.

2022-11-30 18:05 UTC, thelostgus commented on Macacário/Graphs/dijkstra.cpp
> +using namespace std;
Sim

2022-11-30 18:16 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +	// Retorna o valor total do caminho e o caminho
Este código é otimizado para competições de programação e nas competições o caso particular de calcular o peso mínimo é mais comum. Isso não é código pra usar em produção.

Como eu disse em outro comentário, os códigos deste repositório são focados em simplicidade e extensibilidade. Se tentarmos incluir todas as variantes no problema, o código vai ficar muito grande e difícil de usar. É preferível apenas resolver o problema mais simples e manter um código que seja fácil de estender para outras variantes do problema. Também precisamos levar em conta que o código precisa caber no limite de páginas pra final mundial.

2022-11-30 18:17 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +			// v -> No destiono
Nós não estamos na proposta do dijkstra. Estamos resolvendo o caso mais comum do problema para competições de programação.

2022-11-30 18:19 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +array<int, MAXN> dist;
Eu fiz uma pergunta exatamente por não ser especialista em C++. Não sei de onde você tirou que eu entendo disso. Me manter perto do C é uma preferência pessoal exatamente porque eu não manjo de C++.

2022-11-30 18:23 UTC, splucs commented on Macacário/Graphs/dijkstra.cpp
> +	return ivi(dist[t], path);
Onde ocorreu esse debate?
Repetindo o outro comentário: Nós não estamos na proposta do dijkstra. Estamos resolvendo o caso mais comum do problema para competições de programação.

2023-01-08 20:31 UTC, closed without merging